export const cards = [
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: '25',
    expiryMonth: 8,
    placePrice: 37700,
    option: 'CE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 348,
    Avg: 0,
    pl: '25.25',
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: '',
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  },
  {
    product: 'MIS',
    tradingsymbol: 'BANKNIFTY',
    expiryDate: 4,
    expiryMonth: 8,
    placePrice: 37700,
    option: 'PE',
    exchange: 'NFO',
    Qty: 0,
    LTP: 191,
    Avg: 0,
    pl: 3230,
    Chg: 0,
    status: 'closed'
  }
];export const headerData = [
  { tradingsymbol: 'NIFTY 50', price: 17345.45, change: '-1.2' },
  { tradingsymbol: 'NIFTY BANK', price: 38237.4, change: '1.32' }
];export const EventMessage = '';export const OrderPage = [
  {
    time: '10:05:10',
    type: 'SELL',
    product: 'NRML',
    tradingsymbol: 'NIFTY',
    expiryDate: 18,
    expiryMonth: 8,
    placePrice: 17950,
    option: 'CE',
    exchange: 'NFO',
    Qty: '200 / 200',
    Avg: 41.59,
    status: 'COMPLETE'
  },
  {
    time: '10:05:10',
    type: 'SELL',
    product: 'NRML',
    tradingsymbol: 'NIFTY',
    expiryDate: 18,
    expiryMonth: 8,
    placePrice: 17950,
    option: 'CE',
    exchange: 'NFO',
    Qty: '200 / 200',
    Avg: 41.59,
    status: 'COMPLETE'
  },
  {
    time: '10:05:10',
    type: 'SELL',
    product: 'NRML',
    tradingsymbol: 'NIFTY',
    expiryDate: 18,
    expiryMonth: 8,
    placePrice: 17950,
    option: 'CE',
    exchange: 'NFO',
    Qty: '200 / 200',
    Avg: 41.59,
    status: 'COMPLETE'
  },
  {
    time: '10:05:10',
    type: 'SELL',
    product: 'NRML',
    tradingsymbol: 'NIFTY',
    expiryDate: 18,
    expiryMonth: 8,
    placePrice: 17950,
    option: 'CE',
    exchange: 'NFO',
    Qty: '200 / 200',
    Avg: 41.59,
    status: 'COMPLETE'
  }
];export const SideBarData = [
  { tradingsymbol: 'NIFTY AUG FUT', change: '0.84', price: 17560 },
  { tradingsymbol: 'BANKNIFTY AUG FUT', change: '0.6', price: 38301.2 },
  { tradingsymbol: 'HDFCBANK', change: '2.45', price: 1462.05 },
  {
    tradingsymbol: 'ONGC',
    change: '-0.15',
    price: 836.95,
    event: true
  },
  {
    tradingsymbol: 'KOTAKBANK',
    change: '0.58',
    price: 1844.5,
    event: true
  },
  { tradingsymbol: 'SBIN', change: '-2.01', price: 520.4 },
  { tradingsymbol: 'AXISBANK', change: '2.34', price: 745.55 },
  {
    tradingsymbol: 'INDUSINDBK',
    change: '1.34',
    price: 1050.2,
    event: true
  }
]